// Theme Type Definitions for vCard Theme System

export interface ThemeColors {
    background: string;
    backgroundSecondary: string;
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    textSecondary: string;
    border: string;
}

export interface ThemeTypography {
    fontFamily: string;
    headingFont: string;
    baseFontSize: string;
    headingSizes: {
        h1: string;
        h2: string;
        h3: string;
    };
    fontWeights: {
        normal: number;
        medium: number;
        bold: number;
    };
}

export interface ThemeLayout {
    maxWidth: string;
    spacing: {
        xs: string;
        sm: string;
        md: string;
        lg: string;
    };
    borderRadius: {
        sm: string;
        md: string;
        lg: string;
    };
    shadows: {
        sm: string;
        md: string;
        lg: string;
    };
}

export interface ThemeAvatar {
    shape: 'circle' | 'rounded' | 'square';
    size: string;
    borderWidth: string;
    borderColor: string;
    shadow: string;
}

// Header background settings for Visual themes (hero-photo style)
export interface ThemeHeaderBackground {
    useProfilePhoto: boolean;      // Use profile photo as header background
    height: string;                // Height of header area (e.g., "50%", "45%")
    overlayColor: string;          // Overlay color (e.g., "rgba(0,0,0,0.4)")
    overlayOpacity: number;        // Overlay opacity 0-100
    blur: number;                  // Blur amount in pixels (0 = no blur)
    gradientOverlay?: string;      // Optional gradient overlay (e.g., "linear-gradient(...)")
    fallbackGradient: string;      // Fallback gradient when no photo is available
}

// Theme categories - WCAG 2.1 AA compliant design system
export type ThemeCategory =
    | 'aurora'      // Soft, flowing gradient themes
    | 'gradient'    // Bold, vibrant modern gradients
    | 'glass'       // Glassmorphism 2.0 with frosted effects
    | 'minimal'     // Clean, typography-focused
    | 'dark'        // Rich dark mode themes
    | 'visual'      // Hero photo themes
    | 'custom'      // User-created or AI-generated themes
    | 'ai-generated'; // AI-generated themes

export interface Theme {
    id?: number;
    name: string;
    category: ThemeCategory;
    colors: ThemeColors;
    typography: ThemeTypography;
    layout: ThemeLayout;
    avatar: ThemeAvatar;
    headerBackground?: ThemeHeaderBackground; // Optional for Visual themes
    wallpaper?: string; // Optional wallpaper gradient/image for gradient themes
    isSystem: boolean;
    isAIGenerated?: boolean; // True if generated by AI
    createdAt?: string;
}

export interface ThemeSystemResponse {
    themes: Theme[];
    grouped: Record<string, Theme[]>;
    total: number;
}

export interface ThemeUserResponse {
    themes: Theme[];
    total: number;
}

export interface ThemeCreateRequest {
    name: string;
    category?: string;
    colors: ThemeColors;
    typography: ThemeTypography;
    layout: ThemeLayout;
    avatar: ThemeAvatar;
}

export interface ThemeUpdateRequest extends Partial<ThemeCreateRequest> { }

export interface ThemeApplyResponse {
    message: string;
    themeId: number;
    themeName: string;
}

// ==================
// AI Theme Generation Types
// ==================

export interface AIThemePrompt {
    // User inputs for AI theme generation
    mood: string;           // e.g., "professional", "creative", "playful", "elegant"
    industry?: string;      // e.g., "tech", "fashion", "healthcare", "finance"
    colorPreference?: string; // e.g., "warm", "cool", "vibrant", "muted", specific colors
    style?: string;         // e.g., "modern", "minimal", "bold", "soft"
    description?: string;   // Free-form description of desired theme
}

export interface AIThemeResponse {
    success: boolean;
    theme?: Theme;
    message?: string;
    wcagScore?: number;     // 0-100 accessibility score
    suggestions?: string[]; // AI suggestions for improvements
}

// Theme category metadata for UI display
export const THEME_CATEGORY_META: Record<ThemeCategory, { label: string; description: string; icon: string }> = {
    aurora: {
        label: 'Aurora',
        description: 'Soft, flowing gradients inspired by northern lights',
        icon: '🌌'
    },
    gradient: {
        label: 'Gradient',
        description: 'Bold, vibrant modern gradients with high energy',
        icon: '🎨'
    },
    glass: {
        label: 'Glass',
        description: 'Glassmorphism 2.0 with frosted effects',
        icon: '✨'
    },
    minimal: {
        label: 'Minimal',
        description: 'Clean, typography-focused designs',
        icon: '📝'
    },
    dark: {
        label: 'Dark',
        description: 'Rich dark mode themes with accent colors',
        icon: '🌙'
    },
    visual: {
        label: 'Visual',
        description: 'Hero photo themes with profile image as header',
        icon: '📷'
    },
    custom: {
        label: 'Custom',
        description: 'Your personalized themes',
        icon: '🎯'
    },
    'ai-generated': {
        label: 'AI Generated',
        description: 'Themes created by AI based on your preferences',
        icon: '🤖'
    }
};
