#!/usr/bin/env node
// Script to download Google Fonts locally for offline use
// This downloads all fonts specified in theme-definitions.js

const https = require('https');
const fs = require('fs');
const path = require('path');
const { FONT_OPTIONS } = require('../backend/data/theme-definitions');

const FONTS_DIR = path.join(__dirname, '../public/fonts');
const CSS_OUTPUT = path.join(__dirname, '../public/fonts/fonts.css');

// Create fonts directory if it doesn't exist
if (!fs.existsSync(FONTS_DIR)) {
    fs.mkdirSync(FONTS_DIR, { recursive: true });
    console.log('✅ Created fonts directory');
}

/**
 * Download a file from URL to destination
 */
function downloadFile(url, dest) {
    return new Promise((resolve, reject) => {
        const file = fs.createWriteStream(dest);
        https.get(url, (response) => {
            if (response.statusCode !== 200) {
                reject(new Error(`Failed to download ${url}: ${response.statusCode}`));
                return;
            }
            response.pipe(file);
            file.on('finish', () => {
                file.close();
                resolve();
            });
        }).on('error', (err) => {
            fs.unlink(dest, () => { });
            reject(err);
        });
    });
}

/**
 * Fetch Google Fonts CSS and parse font URLs
 */
async function fetchGoogleFontsCss(fontFamily, weights) {
    return new Promise((resolve, reject) => {
        const family = fontFamily.replace(/ /g, '+');
        const weightsStr = weights.join(';');
        const url = `https://fonts.googleapis.com/css2?family=${family}:wght@${weightsStr}&display=swap`;

        https.get(url, {
            headers: {
                'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'
            }
        }, (response) => {
            let data = '';
            response.on('data', chunk => data += chunk);
            response.on('end', () => resolve(data));
        }).on('error', reject);
    });
}

/**
 * Parse font URLs from CSS
 */
function parseFontUrls(css) {
    const urls = [];
    const regex = /url\((https:\/\/[^)]+)\)/g;
    let match;
    while ((match = regex.exec(css)) !== null) {
        urls.push(match[1]);
    }
    return urls;
}

/**
 * Process a single font family
 */
async function processFontFamily(font) {
    try {
        console.log(`\n📥 Processing: ${font.displayName}`);

        // Fetch Google Fonts CSS
        const css = await fetchGoogleFontsCss(font.googleFont, font.weights);

        // Parse font URLs
        const fontUrls = parseFontUrls(css);

        if (fontUrls.length === 0) {
            console.log(`  ⚠️  No font files found for ${font.googleFont}`);
            return { font, css, localPaths: [] };
        }

        console.log(`  Found ${fontUrls.length} font files`);

        // Create font-specific directory
        const fontDir = path.join(FONTS_DIR, font.googleFont.toLowerCase().replace(/ /g, '-'));
        if (!fs.existsSync(fontDir)) {
            fs.mkdirSync(fontDir, { recursive: true });
        }

        // Download each font file
        const localPaths = [];
        for (let i = 0; i < fontUrls.length; i++) {
            const url = fontUrls[i];
            const ext = url.includes('.woff2') ? '.woff2' : '.woff';
            const filename = `${font.googleFont.toLowerCase().replace(/ /g, '-')}-${i}${ext}`;
            const dest = path.join(fontDir, filename);
            const relativePath = `/fonts/${font.googleFont.toLowerCase().replace(/ /g, '-')}/${filename}`;

            try {
                await downloadFile(url, dest);
                localPaths.push({ original: url, local: relativePath });
                process.stdout.write('.');
            } catch (err) {
                console.error(`\n  ❌ Failed to download ${url}:`, err.message);
            }
        }

        console.log(`\n  ✅ Downloaded ${localPaths.length}/${fontUrls.length} files`);

        // Replace URLs in CSS with local paths
        let localCss = css;
        localPaths.forEach(({ original, local }) => {
            localCss = localCss.replace(original, local);
        });

        return { font, css: localCss, localPaths };

    } catch (error) {
        console.error(`  ❌ Error processing ${font.googleFont}:`, error.message);
        return { font, css: '', localPaths: [] };
    }
}

/**
 * Generate complete fonts.css file
 */
function generateFontsCss(results) {
    let css = `/* 
 * Local Google Fonts for vCard Typography
 * Auto-generated by download-fonts.js
 * Total fonts: ${results.length}
 */\n\n`;

    results.forEach(({ font, css: fontCss }) => {
        if (fontCss) {
            css += `/* ${font.displayName} */\n`;
            css += fontCss + '\n\n';
        }
    });

    return css;
}

/**
 * Main execution
 */
async function main() {
    console.log('🚀 Starting Google Fonts download...');
    console.log(`📁 Fonts directory: ${FONTS_DIR}`);
    console.log(`📝 CSS output: ${CSS_OUTPUT}`);
    console.log(`\n💾 Total fonts to download: ${FONT_OPTIONS.length}`);

    const results = [];

    // Process fonts one by one to avoid overwhelming the server
    for (const font of FONT_OPTIONS) {
        const result = await processFontFamily(font);
        results.push(result);

        // Small delay between requests
        await new Promise(resolve => setTimeout(resolve, 500));
    }

    // Generate combined CSS file
    console.log('\n\n📝 Generating fonts.css...');
    const combinedCss = generateFontsCss(results);
    fs.writeFileSync(CSS_OUTPUT, combinedCss, 'utf8');
    console.log(`✅ Generated ${CSS_OUTPUT}`);

    // Summary
    const successful = results.filter(r => r.localPaths.length > 0).length;
    const totalFiles = results.reduce((sum, r) => sum + r.localPaths.length, 0);

    console.log('\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log('✅ Font download complete!');
    console.log(`━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`📊 Fonts processed: ${successful}/${FONT_OPTIONS.length}`);
    console.log(`📦 Total font files: ${totalFiles}`);
    console.log(`💾 Fonts location: ${FONTS_DIR}`);
    console.log(`📝 CSS file: ${CSS_OUTPUT}`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    if (successful < FONT_OPTIONS.length) {
        console.warn(`⚠️  ${FONT_OPTIONS.length - successful} fonts failed to download`);
        console.warn('You may need to re-run the script or check network connection\n');
    }
}

// Run the script
main().catch(error => {
    console.error('\n❌ Fatal error:', error);
    process.exit(1);
});
